version: "3.9"
services:

  near:
    image: nearprotocol/nearup:1.2.0
    command: run localnet --verbose
    init: true
    ports:
      - "127.0.0.1:3030:3030" # near rpc
    healthcheck:
      test: curl -f http://127.0.0.1:3030/status
      interval: 30s
      timeout: 20s
      retries: 3
